name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        run: nvm use 18.18.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: ./deploy.sh
