name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:   # Add this line to allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Add SSH Host Key
        env:
          SERVER_IP: ${{ vars.SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Decode and Save Private Key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" | base64 -d > ~/.ssh/private-key.pem
          chmod 600 ~/.ssh/private-key.pem

      - name: Test SSH Connection
        env:
          SERVER_USER: ${{ vars.SERVER_USER }}
          SERVER_IP: ${{ vars.SERVER_IP }}
        run: |
          ssh -i ~/.ssh/private-key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP exit

      - name: Deploy to Server
        env:
          BUILD_DIR: ${{ vars.BUILD_DIR }}
          SERVER_USER: ${{ vars.SERVER_USER }}
          SERVER_IP: ${{ vars.SERVER_IP }}
          SERVER_DIR: ${{ vars.SERVER_DIR }}
        run: |
          rsync -avz -e "ssh -i ~/.ssh/private-key.pem -o StrictHostKeyChecking=no" --delete -vv $BUILD_DIR/ $SERVER_USER@$SERVER_IP:$SERVER_DIR
