name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production  # Specify the environment here

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Add SSH Host Key
        env:
          SERVER_IP: ${{ vars.SERVER_IP }}  # Referencing the environment variable
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Save Secret to File
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: | 
          echo $PRIVATE_KEY > private-key.pem
          chmod 600 private-key.pem

      - name: Test connection to server
        env:
          SERVER_USER: ${{ vars.SERVER_USER }}  # Referencing the environment variable
          SERVER_IP: ${{ vars.SERVER_IP }}  # Referencing the environment variable
        run: | 
          ssh -i private-key.pem $SERVER_USER@$SERVER_IP

      - name: Deploy to server
        env:
          BUILD_DIR: ${{ vars.BUILD_DIR }}  # Referencing the environment variable
          SERVER_USER: ${{ vars.SERVER_USER }}  # Referencing the environment variable
          SERVER_IP: ${{ vars.SERVER_IP }}  # Referencing the environment variable
          SERVER_DIR: ${{ vars.SERVER_DIR }}  # Referencing the environment variable
        run: |
          rsync -avz -e "ssh -i private-key.pem" --delete -vv $BUILD_DIR/ $SERVER_USER@$SERVER_IP:$SERVER_DIR
